services:
  postgres-db:
    container_name: rickandmorty-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rickandmorty
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: rickandmorty-redis-cache
    image: redis:latest
    ports:
      - 6379:6379
    volumes: 
      - cache:/data
      
volumes:
  cache:
    driver: local
